version: "3.8"
services:
  my-postgres:
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=pgdatabase